# Generated by Django 2.1.1 on 2018-09-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180920_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
