# Generated by Django 2.1.1 on 2018-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_article_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='coauthors',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
