# Generated by Django 2.1.1 on 2018-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180926_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='coauthors',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='follow',
            name='category',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
