# Generated by Django 2.1.1 on 2018-10-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_siteoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
