# Generated by Django 2.1.1 on 2018-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
