# Generated by Django 2.1.1 on 2018-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20181018_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='request',
            field=models.IntegerField(default=0),
        ),
    ]
