# Generated by Django 2.1.1 on 2018-10-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_article_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='likes',
        ),
    ]
