# Generated by Django 2.1.1 on 2018-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_merge_20181019_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
