# Generated by Django 2.1.1 on 2018-10-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20181019_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userbio',
            name='layout',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
        migrations.DeleteModel(
            name='userLikes',
        ),
    ]
