# Generated by Django 2.1.1 on 2018-10-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20181019_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='likes',
        ),
    ]
