# Generated by Django 2.1.1 on 2018-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20181020_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coauthor',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
