# Generated by Django 2.1.1 on 2018-10-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20181020_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coauthor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
