# Generated by Django 2.1.1 on 2018-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_remove_comment_coauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='coauthor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
